Fix SendInBackground for iOS
MindscapeHQ/raygun4maui pull request #15
Opened 2024-03-01 00:44 UTC by ProRedCat

Issue:
During the creation of the RaygunEnvironmentMessage on iOS some fields require that they are accessed on the Main/UI thread. Previously, the provider was silently failing on this and the crash report would never be send to Raygun. This would also cause an infinite loop if ThrowOnError was enabled.

Fix:
Construct the RaygunEnvironmentMessage on the Main/UI thread and then hand back to the thread the SendInBackground call is using.

Testing:
- Confirmed <= v1.4.1 does not send crash report on iOS when using SendInBackground
- Applied MainThread.InvokeOnMainThreadAsync change
- Confirmed that SendInBackground works on iOS, additionally, tested that it still works on Android and other platforms

2024-03-01 00:49 UTC, phillip-haydon approved these changes
Looking good, nice find.

2024-03-03 21:17 UTC, xenolightning requested changes

2024-03-03 21:17 UTC, xenolightning commented on Raygun4Maui/RaygunMauiEnvironmentMessageBuilder.cs
> +            var environmentMessage = MainThread.InvokeOnMainThreadAsync(() =>
Instead of invoking this on the main thread for each and every message, we should look to only query the display info when it's chaning and cache the values.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.devices.idevicedisplay.maindisplayinfochanged?view=net-maui-8.0#microsoft-maui-devices-idevicedisplay-maindisplayinfochanged

We should be able to add a listener here, and update static value for the current width/height etc..

This way there is no need for a lock, or marshalling to the UI thread.

2024-03-06 19:37 UTC, xenolightning requested changes

2024-03-06 19:37 UTC, xenolightning commented on Raygun4Maui/RaygunMauiEnvironmentMessageBuilder.cs
> +        // Instantiated here as RaygunMauiEnvironmentMessageBuilder is lazily initialised so we can be sure the DeviceDisplay has an instance
This comment is confusing, the builder isn't lazy any more?

But we do need to do a manual trigger to update the bounds

Also the member of this class need to be reordered to match our class layout formatting

2024-03-06 19:37 UTC, xenolightning commented on Raygun4Maui.SampleApp/Raygun4Maui.SampleApp.csproj
> +<!--	 <ItemGroup> -->
Should be removed? Or a comment added as to why it's still here

2024-03-06 20:25 UTC, ProRedCat commented on Raygun4Maui.SampleApp/Raygun4Maui.SampleApp.csproj
> +<!--	 <ItemGroup> -->
Outdated, on the latest that is commented in. Was using the pre-1 package for testing

2024-03-06 20:28 UTC, ProRedCat commented on Raygun4Maui/RaygunMauiEnvironmentMessageBuilder.cs
> +        // Instantiated here as RaygunMauiEnvironmentMessageBuilder is lazily initialised so we can be sure the DeviceDisplay has an instance
Changed the comment and fixed the ordering

2024-03-06 20:30 UTC, ProRedCat commented
Testing of the new changes show that the ILogger spam issue goes away and the SendInBackground on iOS works

2024-03-07 01:16 UTC, xenolightning approved these changes
😎

2024-03-10 23:56 UTC, merged