[MC-20]: Update README to improve its grammar
MindscapeHQ/raygun4maui pull request #2
Opened 2023-04-18 04:15 UTC by sumitramanga

Overview
---
**[MC-20](https://raygun.atlassian.net/browse/MC-20): Update README to improve its grammar**
This PR is to implement changes based on the minor improvement points for the MAUI provider. As a part of the Activation Rate work.

We are essentially porting over the documentation changes made in the public docs.

**Author to check:**
- [ ] Builds pass
- [ ] Tested in an alternative environment
- [ ]  Reviewed by another developer
- [ ]  Appropriate documentation written

**Reviewer to check:**
- [ ]  Change has been tested on Beta
- [ ]  Code is written to standards
- [ ]  Appropriate tests have been written

2023-04-18 20:57 UTC, Hamish-taylor requested changes
Only a few minor spelling/grammar issues. The rest looks good!

2023-04-18 20:57 UTC, Hamish-taylor commented on README.md
> +To use these additional configurations, create and initialize a new `RaygunMauiSettings` object as followe:
Minor spelling mistake 'followe'

2023-04-18 20:57 UTC, Hamish-taylor commented on README.md
> +Then add Raygun4Maui to your MauiApp builder This time, passing in the `RaygunMauiSettings` object instead of the API key directly:
Should there be a full stop before 'This'?

2023-04-19 02:26 UTC, sumitramanga commented on README.md
> +Then add Raygun4Maui to your MauiApp builder This time, passing in the `RaygunMauiSettings` object instead of the API key directly:
I think I rely on Grammarly too much nowadays 😅  Thanks for catching these :)

2023-04-19 21:42 UTC, Hamish-taylor requested changes
Just a small word change.

2023-04-19 21:42 UTC, Hamish-taylor commented on README.md
> +To use these additional configurations, create and initialize a new `RaygunMauiSettings` object as followed:
Should it be 'as follows' instead of 'as followed'?

2023-04-20 03:43 UTC, sumitramanga commented on README.md
> +To use these additional configurations, create and initialize a new `RaygunMauiSettings` object as followed:
I thought past tense made sense but happy to change it to present tense :)

2023-04-20 03:45 UTC, sumitramanga commented
@Hamish-taylor I'll leave this PR for you to merge and deploy per what we chatted about in person :)

2023-04-20 21:29 UTC, Hamish-taylor approved these changes

2023-04-20 21:47 UTC, merged